Don't crash when an image can't be read
I have a greyscale Jpeg which was causing the crash.

    TypeError: array shape must be (n,m,3) or (n,m,4)

It was the cover for Devin Townsend's Infinity.

According to
http://www.pygtk.org/pygtk2reference/class-gdkpixbuf.html#function-gdk--pixbuf-new-from-array
pixbuf_new_from_array can't handle anything but RGB. Having said that,
support for non-8-bit-per-channel images could potentially be added.